auto: true
server: true
exclude: README.md, .gitignore
permalink: none
baseurl: 
url: http://opendata.pe
hashtag: '#opendatape'
github_login: 'developmentseed'
github_repo: 'bones'
github_language: 'JavaScript'
